### ISSUE TITLE
Add testing: ws_string type

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#182]
The string type should be tested.

There should be unicode-tests included in this one.

**Comment by xVin** [comment]
Another string issue :o
Can I do this? :-)

**Comment by neithernut** [comment]
Sure.

**Comment by matthiasbeyer** [comment]
Prio changed to critical, as I need functionality from this in my PR #91 which seems to be broken in the string implementation.

**Comment by xVin** [comment]
@matthiasbeyer I won't be able to work on this today, but I'll have a look at it tomorrow morning. Feel free to stop by at the foo pool so that we can discuss.

**Comment by matthiasbeyer** [comment]
I implemented the string type tests. They are failing.

@xVin please fetch my branch "add-string_type_tests" from my repository and use it to implement the fixes. Send all patches together as PR to this repository.

**Comment by xVin** [comment]
Ok, I'll do this starting tomorrow - after the dreaded presentation is over.

**Comment by matthiasbeyer** [comment]
I'm currently doing some further investigation on this and well... the tests are awefully slow (I don't know why) and functions which should only return do not (I don't know why) and the tests fail at points where they shouldn't (and I don't know why).

So, this seems to be a bit more advanced topic here.

**Comment by matthiasbeyer** [comment]
This stuff gets more confusing the more I dig into it.It seems to me that the `ws_string_init()` function segfaults _at return_ (not on the `return` statement, ~~but on the `ret` opcode~~ edit: actually the `leave` opcode causes the segfault). This is _really_ confusing right now.

(I commented out everything which had to do with threading (locks/locking) for the current debugging).

**Comment by TheNeikos** [comment]
Sounds like a buffer overflow to me? Could that be the problem? A stack allocated string overflowing is deadly for the opcodes that follow.

**Comment by matthiasbeyer** [comment]
Nope, I don't find any the like. I'm far beyond this level right now, on the registers level, but the `rbp` and `rsp` registers have the same values right after function enter and before `leave`.

**Comment by neithernut** [comment]
I think I made _some_ progress, I pushed the stuff I did to `add-string_type_tests` in my repo, so you can review the changes I did and use it as a starting point for further investigation.

---

Maybe we should rip out the `is_utf8`-stuff completely. Conversion to raw format may as well be _assumed_ to return an utf8-string.

**Comment by neithernut** [comment]
I got a fairly big part to work.
In the end it was just fixing subtile mistakes and carefully reading the documentation.

**Comment by xVin** [comment]
Sorry for all the trouble with the code. :(

**Comment by neithernut** [comment]
Never mind, it wasn't your fault, really. As you can see, even @matthiasbeyer was clueless. There seem to be just too many subtile things you have to have in mind when working with icu, e.g.:
- Always initialize `err`, because icu functions will refuse to do anything if it is set to an "error-value", it will not even touch `err` itself.
- `u_stringFromUTF8` and some other functions are designed so they can be "abused" for scanning the number of items you need to allocate. However, the length dies not include the termination character. Also, this will result in an overflow error being emitted through `err`. If you forget to reset it after calculating the number of characters you need, the next function will fail if you use the same variable for it.

**Comment by matthiasbeyer** [comment]
Merged your changes and updated the PR.
