### ISSUE TITLE
Q: Documentation to doc/custom/ or into the src/ directory?

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#239]
We (@neithernut and me) started a battle about where documentation belongs to. He means, documentation should go besides the documented functionality, so, into the `src` directory. I think, the `doc/custom/` directory is the destination of the documentation.

Of course, we're talking about extensive documentation here, not function documentation but documentation about functionality.

I would like to hear _all_ opinions!
@waysome/hackers , @waysome/maintainers

**Comment by matthiasbeyer** [comment]
Directly related to #230 and #235

**Comment by neithernut** [comment]
Having the documentation residing in the source directory has _at least_ a few advantages. For example:
- Programmers see the documentation directly when browsing sources. She/he imediately knows about both the existence and location of the documentation.
- Programmers which do not know much about doxygen don't get frustrated when searching for documentation. They are not required to look things up in the doxygen document, which they would have to find/generate in the first place.
- We don't have to mirror the source directory in another documentation directory, which is btw. error phrone. It even reduces the number of inodes the project uses on a file system!
- When moving things around, you don't even have to _think_ about moving the documentation files around, too, because you imediately recognize the files still lying around in the directory you want to remove/which shouldn't contain that file anymore.

**Comment by matthiasbeyer** [comment]
After we discussed the topic, I came to the conclusion that @neithernut s points here are sane and valid.

Anyways, the documentation should be in as few files as possible (prefer longer files over more files) when writing documentation for things. So, we agreed on having the documentation in the `src/` directory.
