### ISSUE TITLE
Add event deserialization

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#375]
The deserializer should also be able to deserialize events.

**Comment by matthiasbeyer** [comment]
For a plugin, sending an event to the software? Can you provide a use case for this?

**Comment by neithernut** [comment]
I can instantly provide two:
- Triggering stored transactions
- Debugging

**Comment by matthiasbeyer** [comment]
Shouldn't triggering of an transaction be a command? I know, it is simpler to implement with events, because events are supposed to trigger transactions, but I guess it would cause less overhead in the code if we simple add a command to trigger a transaction.

What do you think on this _suggestion_/_question_?

---

What do you mean by debugging? Debugging the plugin or our source? And how would an event help with debugging either of them?

**Comment by neithernut** [comment]
An event would be **far** less overhead. **And** you can pass parameters by triggering a transaction through an event (via the value). It's the **one** obvious thing to do here!

---

Debugging transactions in general. You can, e.g., fake an event which usually would be invoked by a key-combo.

**Comment by matthiasbeyer** [comment]
ACK to both points. I'll do this, of course.

**Comment by matthiasbeyer** [comment]
I assume the following format is okay?

``` json
{
   <type> : <event type identifier>
   <name> : <string>
}
```

Do we need an id field? I don't think so, right?

**Comment by neithernut** [comment]
We don't need an "id" field, we do, however, also want an (optional) "value" field (which behaves like a "direct argument" in a statement parameter list).

**Comment by matthiasbeyer** [comment]
Ok.

**Comment by matthiasbeyer** [comment]
This can be closed, I guess.
